### ISSUE TITLE
[Suite de personalización del canal] CP010 - Personalización de canal incorrecto - Fail

### ISSUE THREAD

**Issue by JoshRSx** [JoshRSx/YoutubeProject#10]
#### Precondition
Entrar al canal personal de YouTube Iniciando sesión con una cuenta de Google. 
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Presionar la pestaña "Información Básica"<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26639.png" alt="" />| | OK |
| 2| Presionar el botón "Editar nombre de Canal"<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26638.png" alt="" />| | OK |
| 3| Ingresar el nombre "uno < dos"<br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26644.png" alt="" />| | OK |
| 4| Presionar el botón "Publicar"<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26646.png" alt="" />| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26647.png" alt="" />| Fail ![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_28491.png)|

**Comment by JoshRSx** [comment]
Se intento actualizar el nombre del canal, pero sale un error al momento de publicar el cambio.

**Comment by JoshRSx** [comment]
Se intento actualizar el nombre del canal a "uno < dos", pero sale un error al momento de publicar el cambio.

**Comment by JoshRSx** [comment]
https://youtube-proyect.testquality.com defect [D2](https://youtube-proyect.testquality.com/project/12838/result/2565671/defect/9181).

**Comment by Angel-VII** [comment]
corregido.
