### ISSUE TITLE
[Suite de Publicación de comentarios] C012 - Publicación de comentario incorrecto - Fail

### ISSUE THREAD

**Issue by JoshRSx** [JoshRSx/YoutubeProject#11]
#### Precondition
Entrar al canal personal de YouTube Iniciando sesión con una cuenta de Google. 
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Presionar en la casilla "Añadir un comentario público"<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26629.png" alt="" />| | OK |
| 2| Ingresar comentario "New comment."<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27485.png" alt="" />| |OK |
| 3| Presionar el botón "comentar"<br /><br><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27489.png" alt="" />| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27490.png" alt="" />| Fail ![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_28492.png)|

**Comment by JoshRSx** [comment]
Se intento ingresar en la caja de comentario "New comment", pero sale un error al intentar publicarlo cuando se presiona el botón comentar.

**Comment by JoshRSx** [comment]
https://youtube-proyect.testquality.com defect [D3](https://youtube-proyect.testquality.com/project/12838/result/2565673/defect/9182).

**Comment by Angel-VII** [comment]
Corregido.

**Comment by Angel-VII** [comment]
Corregido.
