### ISSUE TITLE
Error después de subir video

### ISSUE THREAD

**Issue by JoshRSx** [JoshRSx/YoutubeProject#12]
Despues de subir un video el procesamiento del mismo falla con un mensaje "el video es demasiado largo".

![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26723.png)

**Comment by JoshRSx** [comment]
https://youtube-proyect.testquality.com defect [D4](https://youtube-proyect.testquality.com/project/12838/result/2565678/defect/9204).

**Comment by Angel-VII** [comment]
Corregido.
