### ISSUE TITLE
[Suite de Subida de videos] Subida de video insatisfactoria - Fail

### ISSUE THREAD

**Issue by JoshRSx** [JoshRSx/YoutubeProject#14]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Ingresar a Youtube| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26709.png" alt="" />| Fail |
| 2| Hacer click en subir video| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26711.png" alt="" />| Fail |
| 3| Hacer click en subir archivo y seleccionar un video, alternativamente arrastrar un archivo de video a la ventana| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28594.png" alt="" />| Fail |
| 4| Modificar el titulo,descripcion, etc y luego hacer click en siguiente.| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28596.png" alt="" />| Fail |
| 5| Modificar los elementos del video y hacer click en siguiente| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28597.png" alt="" />| Fail |
| 6| Verificar las comprobaciones y hacer click en siguiente.| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28600.png" alt="" />| Fail |
| 7| Modificar la visibilidad y hacer click en guardar.| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28599.png" alt="" />| Fail |
| 8| Observar el video subido erroneamente| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_26723.png" alt="" />| Fail |

**Comment by JoshRSx** [comment]
Al finalizar la subida aparece un error de procesamiento sin solucion

**Comment by JoshRSx** [comment]
https://youtube-proyect.testquality.com defect [D6](https://youtube-proyect.testquality.com/project/12838/result/2577037/defect/9281).

**Comment by Angel-VII** [comment]
Corregido.
