### ISSUE TITLE
[Suite de Búsqueda] Búsqueda incorrecta - Fail

### ISSUE THREAD

**Issue by JoshRSx** [JoshRSx/YoutubeProject#15]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| <strong>Ingresar algún parámetro y/o  palabra relacionado a lo que se desea buscar.</strong>| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28282.png" alt="" />| Fail |
| 2| No se muestran los resultados| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_28556.png" alt="" />| Fail |

**Comment by JoshRSx** [comment]
No se muestran los resultados de la búsqueda por una caída de los servidores de google.

**Comment by JoshRSx** [comment]
https://youtube-proyect.testquality.com defect [D7](https://youtube-proyect.testquality.com/project/12838/result/2577046/defect/9282).

**Comment by Angel-VII** [comment]
Corregido.
